// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6afbLQw6QI0nV__2ACY-pmuA70bI3Fu0',
    appId: '1:475337205463:android:6c066083ead171e17bb292',
    messagingSenderId: '475337205463',
    projectId: 'video-audio-booth',
    storageBucket: 'video-audio-booth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqLwk10NvQqVWXdiRzByFIAyUC3C_cdxk',
    appId: '1:475337205463:ios:0d23db79e86f61b97bb292',
    messagingSenderId: '475337205463',
    projectId: 'video-audio-booth',
    storageBucket: 'video-audio-booth.firebasestorage.app',
    androidClientId: '475337205463-1higtlcr0qtfqn8rp8kek7ogc948q5g4.apps.googleusercontent.com',
    iosClientId: '475337205463-if5s4sjat8tm8tt57ov5savrpkf3korl.apps.googleusercontent.com',
    iosBundleId: 'com.spacecompany.quizTest',
  );
}
